### PR TITLE
Added data architecture ERD

### PR DESCRIPTION
**Pull request by rsundar**
## CHANGES MADE

Added the Entity Relationship Diagram for the Friendship model.

### CODE REVIEW

**Review by jofer86 — CHANGES_REQUESTED** [review]
## :wave: :wave: Hello!, I'm Jorge, and  I'm here to review this Pull Request, let's take a look shall we :eye: :eye: :eye: 
- Changes marked as **[OPTIONAL]** are not hard requirements but are nice to have.
- The ERD file needs to be inside a docs directory as stated [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)
image
- The ERD is on the light side, there is currently only the friendship relation is being shown, we need to also consider comment, posts, and likes, and their relations with the users.
- Just include those relations in your ERD, and you should be good to go.


--------------------------------------------------------------------
Cheers, 
Jorge Fernando Rincón Figueroa.
Technical Support Engineer.
**Slack: @jofer86**

**Comment by rsundar** [comment]
## CHANGES MADE

As requested by @jofer86 the following changes were made.

- The new ERD now shows the comment, posts and likes model and their associations between themselves, and with the user model.

- The diagram was moved into the `docs` folder as per the requirements of the project.

**Review by Torres-ssf — APPROVED** [review]
### Milestone Approved :+1: :tada: :tada: 
Hi there team :hand: 
Great job implementing the requested changes :clap:, Your milestone is approved

There is one thing missing though...
I know this change was not requested in the previous review but it's a requirement. On the user table it's missing a column for the image profile link.
Screenshot from 2020-05-15 08-43-20
Please make this change before moving on.

Good luck in the next Milestone :+1: :smiley: 
Happy coding :computer: 

**Sergio Torres**

**Comment by rsundar** [comment]
Thanks @Torres-ssf We will make that change before submitting the next milestone.

**Pull request merged**
