### PR TITLE
Milestone 5

### PR DESCRIPTION
**Pull request by rsundar**
## FEATURES IMPLEMENTED

The following feature were implemented as part of milestone 5:

- Created a friendship model to associate friends in the app.
- A logged in user can request, confirm or delete friendship requests.

### CODE REVIEW

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Great job @rsundar, @mariobarrioss:clap:, Let's now take care of the following:**
:point_right: I can't find your linter check report. It seems not to be setup properly. Please fix this.
:point_right: Timeline should display posts of logged in user and his friends. Currently, it displays all posts - including posts from those who are not friends.
:point_right: Posts in timeline should show number of comments and likes.



:point_right: Add unit and integration tests for your project.



:point_right: You have a lot of conditionals in your views. Extract them into helper methods where they are necessary. See this [article](http://codefol.io/posts/Where-Do-I-Put-My-Code) and this [one](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers).




_**Kindly make these changes and submit another code review request.**_

**Any questions? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

**Comment by rsundar** [comment]
## CHANGES MADE

The following changes were made as per the request of @mosesogwo :

- Unit and Integration tests were added,
- A User's posts on timeline can only be viewed by others if they are friends with them.
- The conditional logic in the views was extracted out into a partial.
- Added number of counts and likes to the user's comment page.

**Review by kobiyoyo — APPROVED** [review]
# Project Approved :thumbsup:
## Hello Team ,  You have done a great job with this project. :clap:
The test you are to write also includes:
- Posts
- Comments 
- Like
### Just keep that in mind for next milestone
#### You can go ahead and merge !!!

**Comment by rsundar** [comment]
Thank you @kobiyoyo @mosesogwo we will add the unit and integrations for the comments, likes, posts, and users for the next milestone.

**Pull request merged**
